services:
  amazon-ynab-sync:
    image: ghcr.io/graftechnology/amazon-ynab-sync:latest
    container_name: amazon-ynab-sync
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    environment:
      # Override defaults if needed
      IMAP_INCOMING_PORT: 993
      IMAP_TLS: "true"
      IMAP_INBOX_NAME: "[Gmail]/All Mail"
      HISTORICAL_SEARCH_NUM_EMAILS: 500
      YNAB_ACCEPTABLE_DATE_DIFFERENCE: 6
      YNAB_ACCEPTABLE_DOLLAR_DIFFERENCE: 0.5
    # Health check to ensure container is working
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
